# SPDX-License-Identifier: GPL-2.0-only
# 
# MLStreams
# Copyright (c) 2001-2023, Bryan Hinton
# All rights reserved.

include Make.defines

LIBS		= -lpthread -lrt -lnsl -lsocket -lresolv -L$(LIBDIR)/lmscpp
CPPFLAGS 	= -D_REENTRANT

OBJ = $(ECHOSERV_FILE:cpp=o)
TARGET = $(ECHOSERV)

all : $(TARGET)

$(TARGET) : $(OBJ)
	$(CPP) -o $@ $(OBJ) $(LIBS)

.cpp.o :
	$(CPP) $(CPPFLAGS) -c $(<)

clean :
	$(RM) -f $(ECHOSERV) *.o *.rpo core

again:
	$(MAKE) clean
	$(MAKE) $(ECHOSERV)
